from basicsearch_lib.boardtypes import TileBoard
n_by_8 = TileBoard(8, [1,2,3,4, None, 6, 7,5, 8])
print(n_by_8)
print("n_by_8.board:", end="")
print(n_by_8.board)
print("n_by_8 Goal State:")
print(n_by_8.get_goal_state(n_by_8.n))
print("is n_by_8 solvable:")
print(n_by_8.solvable())
print("n_by_8 Goal State.board:", end=" ")
print(n_by_8.get_goal_state(n_by_8.n).board)
print("Is n_by_8 solved?", end=" ")
print(n_by_8.solved())
print("Location of 'None' in n_by_8", end=" ")
print(n_by_8.find_item_idx(None))
print(n_by_8.get_actions())